### ISSUE TITLE
Error: File is larger than 5242880 bytes

### ISSUE THREAD

**Issue by smithandrewk** [lxaw/Delta#2]
Clicked to upload a file that is a pretty standard size (9.3M), but received the error **Error: File is larger than 5242880 bytes**. I suppose the fix is an environment variable in Django to allow for larger files.

**Comment by lxaw** [comment]
Should be fixed with https://github.com/lxaw/Delta/commit/6ffc6867bbf74eccccb0b743bdb1df5d85bc64c0
